# Fate prediction configuration
# Core parameters (required)
project_name: "fate_prediction.testing_docker_osx"
h5ad_path: "/data/larry_binned.h5ad"  # This should be mounted or passed as env var
time_key: "median_qbin"

# Optional parameters with defaults
weight_key: "W"
time_point: 2.0
ckpt_frequency: 1
save_last_ckpt: true
keep_ckpts: 3
monitor: "epoch_validation_loss"
n_seeds: 1
seeds: [0]
n_eval: 2000
swa_lrs: 0.00001  # 1e-5
mu_hidden: [512, 512]
sigma_hidden: [32, 32]
train_epochs: 2500
train_lr: 0.00004  # 4e-5
train_step_size: 1500
mu_dropout: 0.0
sigma_dropout: 0.0
batch_size: 2048
coef_diffusion: 1.0
diffeq_type: "SDE"
use_key: "X_pca"
potential_type: "fixed"
latent_dim: 50
velocity_ratio_params:
  target: 2.5
  enforce: 100
  method: "square" 


# Don't set here, should be passed securely at runtime
wandb_api_key: ""