experiments:
  # Varying mu_hidden with fixed sigma_hidden [32, 32]
  - id: 1
    mu_hidden: [32, 32]
    sigma_hidden: [32, 32]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
  - id: 2
    mu_hidden: [64, 64]
    sigma_hidden: [32, 32]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
  - id: 3
    mu_hidden: [128, 128]
    sigma_hidden: [32, 32]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
  - id: 4
    mu_hidden: [256, 256]
    sigma_hidden: [32, 32]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
  - id: 5
    mu_hidden: [512, 512]
    sigma_hidden: [32, 32]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
  - id: 6
    mu_hidden: [1024, 1024]
    sigma_hidden: [32, 32]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
  - id: 7
    mu_hidden: [2048, 2048]
    sigma_hidden: [32, 32]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
    
  # Varying mu_hidden with fixed sigma_hidden [512, 512]
  - id: 8
    mu_hidden: [32, 32]
    sigma_hidden: [512, 512]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
  - id: 9
    mu_hidden: [64, 64]
    sigma_hidden: [512, 512]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
  - id: 10
    mu_hidden: [128, 128]
    sigma_hidden: [512, 512]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
  - id: 11
    mu_hidden: [256, 256]
    sigma_hidden: [512, 512]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
  - id: 12
    mu_hidden: [512, 512]
    sigma_hidden: [512, 512]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
    
  # Varying mu_hidden with fixed sigma_hidden [2048, 2048]
  - id: 13
    mu_hidden: [32, 32]
    sigma_hidden: [2048, 2048]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
  - id: 14
    mu_hidden: [64, 64]
    sigma_hidden: [2048, 2048]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
  - id: 15
    mu_hidden: [128, 128]
    sigma_hidden: [2048, 2048]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
  - id: 16
    mu_hidden: [256, 256]
    sigma_hidden: [2048, 2048]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
  - id: 17
    mu_hidden: [512, 512]
    sigma_hidden: [2048, 2048]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
  - id: 18
    mu_hidden: [1024, 1024]
    sigma_hidden: [2048, 2048]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
  - id: 19
    mu_hidden: [2048, 2048]
    sigma_hidden: [2048, 2048]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
    
  # Varying sigma_hidden with fixed mu_hidden [32, 32]
  - id: 20
    mu_hidden: [32, 32]
    sigma_hidden: [32, 32]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
  - id: 21
    mu_hidden: [32, 32]
    sigma_hidden: [64, 64]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
  - id: 22
    mu_hidden: [32, 32]
    sigma_hidden: [128, 128]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
  - id: 23
    mu_hidden: [32, 32]
    sigma_hidden: [256, 256]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
  - id: 24
    mu_hidden: [32, 32]
    sigma_hidden: [512, 512]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
  - id: 25
    mu_hidden: [32, 32]
    sigma_hidden: [1024, 1024]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
  - id: 26
    mu_hidden: [32, 32]
    sigma_hidden: [2048, 2048]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
    
  # Varying sigma_hidden with fixed mu_hidden [512, 512]
  - id: 27
    mu_hidden: [512, 512]
    sigma_hidden: [32, 32]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
  - id: 28
    mu_hidden: [512, 512]
    sigma_hidden: [64, 64]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
  - id: 29
    mu_hidden: [512, 512]
    sigma_hidden: [128, 128]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
  - id: 30
    mu_hidden: [512, 512]
    sigma_hidden: [256, 256]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
  - id: 31
    mu_hidden: [512, 512]
    sigma_hidden: [512, 512]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
  - id: 32
    mu_hidden: [512, 512]
    sigma_hidden: [1024, 1024]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
  - id: 33
    mu_hidden: [512, 512]
    sigma_hidden: [2048, 2048]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
    
  # Varying sigma_hidden with fixed mu_hidden [2048, 2048]
  - id: 34
    mu_hidden: [2048, 2048]
    sigma_hidden: [32, 32]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
  - id: 35
    mu_hidden: [2048, 2048]
    sigma_hidden: [64, 64]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
  - id: 36
    mu_hidden: [2048, 2048]
    sigma_hidden: [128, 128]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
  - id: 37
    mu_hidden: [2048, 2048]
    sigma_hidden: [256, 256]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
  - id: 38
    mu_hidden: [2048, 2048]
    sigma_hidden: [512, 512]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
  - id: 39
    mu_hidden: [2048, 2048]
    sigma_hidden: [1024, 1024]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
  - id: 40
    mu_hidden: [2048, 2048]
    sigma_hidden: [2048, 2048]
    velocity_ratio_target: 2.5
    velocity_ratio_enforce: 100
    
  # Varying E (velocity_ratio_target) with best settings
  - id: 41
    mu_hidden: [512, 512]
    sigma_hidden: [32, 32]
    velocity_ratio_target: 1
    velocity_ratio_enforce: 100
  - id: 42
    mu_hidden: [512, 512]
    sigma_hidden: [32, 32]
    velocity_ratio_target: 10
    velocity_ratio_enforce: 100
  - id: 43
    mu_hidden: [512, 512]
    sigma_hidden: [32, 32]
    velocity_ratio_target: 50
    velocity_ratio_enforce: 100
  - id: 44
    mu_hidden: [512, 512]
    sigma_hidden: [32, 32]
    velocity_ratio_target: 90
    velocity_ratio_enforce: 100
  - id: 45
    mu_hidden: [512, 512]
    sigma_hidden: [32, 32]
    velocity_ratio_target: 100
    velocity_ratio_enforce: 100

# Common parameters for all experiments
common:
  train_epochs: 2500
  train_lr: 1e-4
  train_step_size: 1500
  n_seeds: 5
  n_eval: 2000
  swa_lrs: 1e-5
  mu_dropout: 0
  sigma_dropout: 0
  batch_size: 2048
  potential_type: "fixed"
  coef_g: 1
  velocity_ratio_method: "square"